-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY,sum(bs.SALES*b.PRICE) as TOTAL_SALES
FROM BOOK as b 
JOIN BOOK_SALES as bs
ON b.BOOK_ID = bs.BOOK_ID
JOIN AUTHOR as a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(bs.SALES_DATE, "%Y-%m") ='2022-01'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC;
