-- 코드를 작성해주세요
SELECT ii.ITEM_ID, ii.ITEM_NAME
FROM ITEM_INFO as ii
JOIN ITEM_TREE as it
on ii.ITEM_ID = it.ITEM_ID
WHERE ii.ITEM_ID in (SELECT ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID is NULL)
ORDER BY ii.ITEM_ID;