-- 코드를 입력하세요
-- ONLINE_SALE : 온라인 상품 판매 정보를 담음
-- OFFLINE_SALE : 오프라인 상품 판매 정보를 담음
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m")='2022-03'
UNION
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d")AS SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m")='2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
