-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE,
PRODUCT_ID,NULLIF(USER_ID,"NULL") AS USER_ID,SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'
union 
SELECT DATE_Format(SALES_DATE, '%Y-%m-%d') as SALES_DATE,PRODUCT_ID, 
Null as USER_ID,
SALES_AMOUNT
from OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-03'
order by SALES_DATE, PRODUCT_ID, USER_ID;