-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, ROUND(a.DAILY_FEE*30*(100-c.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a 
join CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
join CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
ON a.CAR_TYPE = c.CAR_TYPE
where a.CAR_ID not in (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE END_DATE > '2022-11-01' and START_DATE < '2022-12-01') and c.DURATION_TYPE = '30일 이상' and a.CAR_TYPE IN ('세단','SUV')
group by a.CAR_ID
having FEE>=500000 AND FEE<2000000
order by FEE desc, a.CAR_TYPE, a.CAR_ID desc;