-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID,  count(CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m")between '2022-08' and '2022-10'
and CAR_ID in (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5)
GROUP BY MONTH(START_DATE), CAR_ID
having count(HISTORY_ID) != 0
ORDER BY MONTH, CAR_ID DESC;
