-- 코드를 입력하세요
-- USED_GOODS_BOARD : 중고거래 게시판 정보
-- USED_GOODS_REPLY : 중고거래 게시판 첨부파일 정보 
SELECT GB.TITLE, GB.BOARD_ID,GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS GB
JOIN USED_GOODS_REPLY AS GR
ON GB.BOARD_ID = GR.BOARD_ID
WHERE DATE_FORMAT(GB.CREATED_DATE,"%Y-%m") = '2022-10'
ORDER BY GR.CREATED_DATE, TITLE;